name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      deployments: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@goapptiv'
      - name: Log in to registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: Install Packages
        run: npm install
      - name: Install Packages
        run: npm install
      - name: Build Package
        run: npm run build
      - name: Publish Library
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
